{
  "formatVersion": "1.1",
  "component": {
    "group": "ehn.techiop.hcert",
    "module": "hcert-kotlin",
    "version": "1.4.0-CUSTOM",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mo3nz5jgxzd4pgmlmtivydlqxm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "hcert-kotlin-metadata-1.4.0-CUSTOM.jar",
          "url": "hcert-kotlin-1.4.0-CUSTOM.jar",
          "size": 59783,
          "sha512": "a51617ef82189c3bb0704c1b9f83091912bc197317abb144fb2b27ca853d865cc47eec712267d1b073f6fde3409904b8078b62effbf2d025277aa9ecb9170436",
          "sha256": "d91423aaeb32146d2111fb5978995a2dc859e9853b8c7834f48db8562c772c6a",
          "sha1": "23f0e1a6d77407804b03f712754eddbca7801280",
          "md5": "c1cc448084e0a3fdb79b83038cc9300b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../hcert-kotlin-js/1.4.0-CUSTOM/hcert-kotlin-js-1.4.0-CUSTOM.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-js",
        "version": "1.4.0-CUSTOM"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../hcert-kotlin-js/1.4.0-CUSTOM/hcert-kotlin-js-1.4.0-CUSTOM.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-js",
        "version": "1.4.0-CUSTOM"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "false",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvm/1.4.0-CUSTOM/hcert-kotlin-jvm-1.4.0-CUSTOM.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvm",
        "version": "1.4.0-CUSTOM"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "false",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvm/1.4.0-CUSTOM/hcert-kotlin-jvm-1.4.0-CUSTOM.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvm",
        "version": "1.4.0-CUSTOM"
      }
    },
    {
      "name": "jvmDataGenApiElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "true",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvmdatagen/1.4.0-CUSTOM/hcert-kotlin-jvmdatagen-1.4.0-CUSTOM.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvmdatagen",
        "version": "1.4.0-CUSTOM"
      }
    },
    {
      "name": "jvmDataGenRuntimeElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "true",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvmdatagen/1.4.0-CUSTOM/hcert-kotlin-jvmdatagen-1.4.0-CUSTOM.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvmdatagen",
        "version": "1.4.0-CUSTOM"
      }
    }
  ]
}
