{
  "formatVersion": "1.1",
  "component": {
    "group": "ehn.techiop.hcert",
    "module": "hcert-kotlin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "2dmu3nt2izdpzc3ofnbz7bs5zq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "hcert-kotlin-metadata-1.4.0-SNAPSHOT.jar",
          "url": "hcert-kotlin-1.4.0-SNAPSHOT.jar",
          "size": 59783,
          "sha512": "c8615de2e1674649532ba00525f2864e7a2a14b087d315397969f44acf5dd9a01556cc3817e85a9eb600f91bddd279fb804d02f00c0a36e8d4407d784272329e",
          "sha256": "bf2f4fe252c2185168b05c84b263dfb23c2ef10b5eb30e342c0a1daa91b4e815",
          "sha1": "74ca313772d771169289f98a656cbf40aa6b4227",
          "md5": "2302503f0963b1621801c0da3ddb6bf1"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "false",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvm/1.4.0-SNAPSHOT/hcert-kotlin-jvm-1.4.0-SNAPSHOT.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvm",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "false",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvm/1.4.0-SNAPSHOT/hcert-kotlin-jvm-1.4.0-SNAPSHOT.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvm",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmDataGenApiElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "true",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvmdatagen/1.4.0-SNAPSHOT/hcert-kotlin-jvmdatagen-1.4.0-SNAPSHOT.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvmdatagen",
        "version": "1.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmDataGenRuntimeElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "true",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hcert-kotlin-jvmdatagen/1.4.0-SNAPSHOT/hcert-kotlin-jvmdatagen-1.4.0-SNAPSHOT.module",
        "group": "ehn.techiop.hcert",
        "module": "hcert-kotlin-jvmdatagen",
        "version": "1.4.0-SNAPSHOT"
      }
    }
  ]
}
