{
  "formatVersion": "1.1",
  "component": {
    "url": "../../hcert-kotlin/1.4.0-SNAPSHOT/hcert-kotlin-1.4.0-SNAPSHOT.module",
    "group": "ehn.techiop.hcert",
    "module": "hcert-kotlin",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "2dmu3nt2izdpzc3ofnbz7bs5zq"
    }
  },
  "variants": [
    {
      "name": "jvmDataGenApiElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "true",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "hcert-kotlin-jvmdatagen-1.4.0-SNAPSHOT.jar",
          "url": "hcert-kotlin-jvmdatagen-1.4.0-SNAPSHOT.jar",
          "size": 331499,
          "sha512": "6ac51fc98558bf4c2ef46fc40a92d6b3e316420745ccb933172d44da875aca70bdf643f825043f926d5c23ca07e23c0cde974af6a7b3ad123157167a0021fac5",
          "sha256": "8d474ced996ffda91649f5442e593822d01a6ee5fd2985a91c031b8e2b4e9c48",
          "sha1": "03504f51614368ccebd9b27e8fbdef7a9bbedf73",
          "md5": "34dc16fb63289e5e1f891106866dc813"
        }
      ]
    },
    {
      "name": "jvmDataGenRuntimeElements-published",
      "attributes": {
        "ehn.techiop.hcert.faults": "true",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "com.augustcellars.cose",
          "module": "cose-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "javase",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15to18",
          "version": {
            "requires": "1.68"
          }
        },
        {
          "group": "net.pwall.json",
          "module": "json-kotlin-schema",
          "version": {
            "requires": "0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "hcert-kotlin-jvmdatagen-1.4.0-SNAPSHOT.jar",
          "url": "hcert-kotlin-jvmdatagen-1.4.0-SNAPSHOT.jar",
          "size": 331499,
          "sha512": "6ac51fc98558bf4c2ef46fc40a92d6b3e316420745ccb933172d44da875aca70bdf643f825043f926d5c23ca07e23c0cde974af6a7b3ad123157167a0021fac5",
          "sha256": "8d474ced996ffda91649f5442e593822d01a6ee5fd2985a91c031b8e2b4e9c48",
          "sha1": "03504f51614368ccebd9b27e8fbdef7a9bbedf73",
          "md5": "34dc16fb63289e5e1f891106866dc813"
        }
      ]
    }
  ]
}
